### ISSUE TITLE
Deploy the custom application

### ISSUE THREAD

**Issue by sastafford** [rjrudin/slush-marklogic-spring-boot#25]
As a developer
I want to TITLE
So that I can easily deploy the application to a server

Steps
1. Include application plugin for build.gradle file
2. Include the mlcp jar files to support upload functionality.  If these files are not included then the upload form will not work when deploying the application

**Comment by rjrudin** [comment]
I think this is already addressed via Spring Boot's "assemble" task. With that, Gradle will package up the entire app as an executable JAR file. It can then easily be installed as a service:

http://docs.spring.io/spring-boot/docs/current/reference/html/deployment-install.html

I think that's the better option vs Gradle's application plugin, which is why the Gradle file enables it by default. A developer can always choose to use the application plugin on the generated project too - I just don't think it's worth enabling by default, because the Spring Boot option is already there.
